services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: hermes-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-hermes}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}

volumes:
  postgres_data:
    driver: local
